name: Soroban Contract # name it whatever you like
on:
  push:
    tags:
      - "v*" # triggered whenever a new tag (prefixed with "v") is pushed to the repository

permissions: # required permissions for the workflow
  id-token: write
  contents: write
  attestations: write

jobs:
  release-contract-a:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: "Sport Prediction ONEXT v2 Contract Release"
      home_domain: "awesome.com" # home domain for the contract
      relative_path: "contracts/hello-world" # Path to your contract (update this)
      package: "betting_contract" # Package name from Cargo.toml
    secrets: # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }} # don't modify this line
